version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
